import React from 'react';

const InsightsPanel = ({ loading, insightText }) => {
    return (
        <div className="card h-full">
            <div className="card-header pb-2">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ width: '1.25rem', height: '1.25rem', color: 'hsl(var(--primary))' }}>
                            <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                        </svg>
                        <span className="text-sm font-medium" style={{ color: 'hsl(var(--primary))' }}>AI Powered</span>
                    </div>
                </div>
                <h2 className="card-title text-xl ai-gradient-text" style={{ background: 'linear-gradient(to right, hsl(var(--primary)), hsl(0 85% 65%))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', margin: 0 }}>Smart Insights</h2>
                <p className="text-xs text-muted-foreground mt-1">Personalized analysis powered by Google Gemini AI</p>
            </div>
            <div className="card-content pt-4">
                {loading ? (
                    <div className="flex flex-col gap-3 items-center justify-center p-4">
                        <div className="flex gap-1">
                            <div className="animate-bounce" style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'hsl(var(--primary))', animationDelay: '0ms' }}></div>
                            <div className="animate-bounce" style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'hsl(var(--primary))', animationDelay: '150ms' }}></div>
                            <div className="animate-bounce" style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'hsl(var(--primary))', animationDelay: '300ms' }}></div>
                        </div>
                        <span className="text-sm text-muted-foreground">AI is analyzing your spending patterns...</span>
                    </div>
                ) : insightText ? (
                    <div>
                        <div className="text-sm leading-relaxed mb-4">{insightText}</div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground border-t pt-2 mt-2">
                            <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ width: '0.75rem', height: '0.75rem' }}>
                                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
                            </svg>
                            <span>Generated by AI • Powered by Google Gemini</span>
                        </div>
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center p-6 text-center text-muted-foreground">
                        <svg className="w-10 h-10 mb-2 opacity-20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ width: '2.5rem', height: '2.5rem' }}>
                            <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                        </svg>
                        <p className="text-sm">AI insights will appear here when there is enough spending data to analyze.</p>
                        <p className="text-xs mt-1">Add more expenses to unlock personalized insights!</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default InsightsPanel;
